#!/usr/bin/env node
// Brings up the disposable Lago environment for the integration suite and writes its
// connection details to .env.test.
//
// Lago normally requires an interactive signup before any API key exists. Its migration
// script can seed an organization instead, and will adopt a caller-supplied key verbatim
// when LAGO_ORG_API_KEY is set, so the credential is known before the stack is even up and
// no GraphQL round trip is needed to discover it.
import { spawnSync } from 'node:child_process';
import { generateKeyPairSync } from 'node:crypto';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const ENV_FILE = resolve(root, '.env.lago');
const TEST_ENV_FILE = resolve(root, '.env.test');

const BASE_URL = process.env.LAGO_BASE_URL ?? 'http://localhost:3210';
const API_KEY = process.env.LAGO_ORG_API_KEY ?? 'n8n-nodes-lago-test-key';

function die(message) {
	console.error(`\n✖ ${message}`);
	process.exit(1);
}

/**
 * Lago refuses to boot without an RSA private key — it signs webhook JWTs with it — and
 * expects it base64 encoded. It is generated once and kept in .env.lago so repeated `up`
 * runs reuse the same key rather than invalidating anything already signed.
 */
function ensureRsaKey() {
	if (existsSync(ENV_FILE)) {
		const existing = readFileSync(ENV_FILE, 'utf8').match(/^LAGO_RSA_PRIVATE_KEY=(.+)$/m);
		if (existing) return existing[1];
	}

	const { privateKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
	const pem = privateKey.export({ type: 'pkcs1', format: 'pem' }).toString();
	const encoded = Buffer.from(pem).toString('base64');

	writeFileSync(
		ENV_FILE,
		`# Generated by scripts/lago-dev.mjs. Not secret — this environment is disposable.\n` +
			`LAGO_RSA_PRIVATE_KEY=${encoded}\n` +
			`LAGO_ORG_API_KEY=${API_KEY}\n`,
		'utf8',
	);
	return encoded;
}

function compose(args, options = {}) {
	return spawnSync('docker', ['compose', '--env-file', ENV_FILE, ...args], {
		cwd: root,
		encoding: 'utf8',
		stdio: options.capture ? 'pipe' : 'inherit',
		...options,
	});
}

async function waitForHealth(timeoutMs = 300_000) {
	const deadline = Date.now() + timeoutMs;
	process.stdout.write('> waiting for lago to become healthy');
	while (Date.now() < deadline) {
		try {
			const response = await fetch(`${BASE_URL}/health`);
			if (response.ok) {
				process.stdout.write(' ok\n');
				return;
			}
		} catch {
			// Not accepting connections yet.
		}
		process.stdout.write('.');
		await new Promise((r) => setTimeout(r, 3000));
	}
	process.stdout.write('\n');
	die(`Lago did not become healthy within ${timeoutMs / 1000}s. Try: docker compose logs api`);
}

/**
 * Proves the seeded key authenticates against the REST API exactly as the node's credential
 * will. A healthy container only means Rails is up; it says nothing about whether the
 * seeding task actually ran.
 */
async function verifyApiKey() {
	const response = await fetch(`${BASE_URL}/api/v1/billing_entities`, {
		headers: { Authorization: `Bearer ${API_KEY}` },
	});
	if (!response.ok) {
		die(
			`The seeded API key was rejected (${response.status}). ` +
				`The organization seeding step may not have run. Try: docker compose logs migrate`,
		);
	}
	const body = await response.json();
	const entities = body?.billing_entities ?? [];
	if (entities.length === 0) {
		die('Lago authenticated but reported no billing entity, so the organization was not seeded.');
	}
	return entities[0];
}

async function main() {
	const command = process.argv[2] ?? 'up';

	if (command === 'down') {
		if (existsSync(ENV_FILE)) {
			compose(['down', '--volumes', '--remove-orphans']);
			rmSync(ENV_FILE, { force: true });
		}
		rmSync(TEST_ENV_FILE, { force: true });
		return;
	}

	if (command !== 'up') die(`Unknown command "${command}". Use "up" or "down".`);

	const rsaKey = ensureRsaKey();
	const up = compose(['up', '--detach', '--wait'], {
		env: { ...process.env, LAGO_RSA_PRIVATE_KEY: rsaKey, LAGO_ORG_API_KEY: API_KEY },
	});
	if (up.status !== 0) die('docker compose up failed');

	await waitForHealth();
	const billingEntity = await verifyApiKey();

	writeFileSync(
		TEST_ENV_FILE,
		`# Generated by scripts/lago-dev.mjs. Recreated on every lago:up.\n` +
			`LAGO_BASE_URL=${BASE_URL}\n` +
			`LAGO_API_KEY=${API_KEY}\n`,
		'utf8',
	);

	console.log(`\n✔ Lago is ready at ${BASE_URL}`);
	console.log(`  billing entity : ${billingEntity.code ?? billingEntity.name}`);
	console.log(`  credentials    : written to .env.test`);
	console.log(`\n  Run the integration suite with: npm test`);
	console.log(`  Tear it down with:              npm run lago:down`);
}

await main();
